### PR TITLE
DPAD fix, Stretched Vs Native Resolution compile option + dynamic calculation, project compile properties update.

### PR DESCRIPTION
**Pull request by a7omic**
DPAD Fix 
- One of the angles was incorrect. (23 should be -23)

Stretched Vs Native Resolution + Dynamic Calculation
- Added the compile option **STRETCHED**.  
- If **STRETCHED** is defined the window size will be be set to the size returned by the hardware and the buffer will be set the the width and height passed in by the calling app.
- if **STRETCHED** is not defined the window size will be based on the size returned by the hardware and the width/height provided by the app.  It will calculate the best size that will fill most of the screen while maintaining the native aspect ratio. The the size of window and size of buffer are assigned these calculated values.

Project compile properties update
- I unchecked Debug (-g) box in the project properties for the Device-Release configuration.

### CODE REVIEW

**Comment by jnicholl** [comment]
On the whole, looks pretty good. Can I just confirm what the default value of **STRETCHED** is?

**Comment by a7omic** [comment]
In my project I do not have __STRETCHED __ defined in my symbols so it will not execute this code, therefor it runs with the native resolution.  If you want it to stretch by default then you would need to add the symbol.  Would you suggest a different/better way to do this?

**Comment by jnicholl** [comment]
I guess that's okay. I can't think of a better way to do it. It's a bit unfortunate that this will change the default behavior of some other apps, but there's no convenient way to pass the information down. Perhaps something could be done around the SDL_FULLSCREEN flag being requested at runtime, rather than having to compile SDL differently? 
Maybe that should be a TODO for later. 

Approved, I'll just wait for any more comments before merging.

**Comment by a7omic** [comment]
I agree, I just didn't want to modify that part in case you had other plans. Would you like me to switch it around to be **nativeaspect** or something like that so that the current functionality is the default, or you could add **STRETCHED** to the default project setup.

**Comment by jnicholl** [comment]
I think it'll be fine. I'll merge it in.
Thanks!

**Pull request merged**
